export const data = [
  {
    "Date": "15-Jan-67",
    "SB": "I ",
    "Attendance": 61946,
    "QB  Winner": "Bart Starr",
    "Coach Winner": "Vince Lombardi",
    "Winner": "Green Bay Packers",
    "Winning Pts": 35,
    "QB Loser": "Len Dawson",
    "Coach Loser": "Hank Stram",
    "Loser": "Kansas City Chiefs",
    "Losing Pts": 10,
    "MVP": "Bart Starr",
    "Stadium": "Memorial Coliseum",
    "City": "Los Angeles",
    "State": "California",
    "Point Difference": 25,
    "Referee": "",
    "Umpire": "",
    "Head Linesman": "",
    "Line Judge": "",
    "Field Judge": "",
    "Back Judge": "",
    "Side Judge": ""
  },
  {
    "Date": "14-Jan-68",
    "SB": "II ",
    "Attendance": 75546,
    "QB  Winner": "Bart Starr",
    "Coach Winner": "Vince Lombardi",
    "Winner": "Green Bay Packers",
    "Winning Pts": 33,
    "QB Loser": "Daryle Lamonica",
    "Coach Loser": "John Rauch",
    "Loser": "Oakland Raiders",
    "Losing Pts": 14,
    "MVP": "Bart Starr",
    "Stadium": "Orange Bowl",
    "City": "Miami",
    "State": "Florida",
    "Point Difference": 19,
    "Referee": "",
    "Umpire": "",
    "Head Linesman": "",
    "Line Judge": "",
    "Field Judge": "",
    "Back Judge": "",
    "Side Judge": ""
  },
  {
    "Date": "12-Jan-69",
    "SB": "III ",
    "Attendance": 75389,
    "QB  Winner": "Joe Namath",
    "Coach Winner": "Weeb Ewbank",
    "Winner": "New York Jets",
    "Winning Pts": 16,
    "QB Loser": "Earl Morrall, Johnny Unitas",
    "Coach Loser": "Don Shula",
    "Loser": "Baltimore Colts",
    "Losing Pts": 7,
    "MVP": "Joe Namath",
    "Stadium": "Orange Bowl",
    "City": "Miami",
    "State": "Florida",
    "Point Difference": 9,
    "Referee": "",
    "Umpire": "",
    "Head Linesman": "",
    "Line Judge": "",
    "Field Judge": "",
    "Back Judge": "",
    "Side Judge": ""
  },
  {
    "Date": "11-Jan-70",
    "SB": "IV ",
    "Attendance": 80562,
    "QB  Winner": "Len Dawson, Mike Livingston",
    "Coach Winner": "Hank Stram",
    "Winner": "Kansas City Chiefs",
    "Winning Pts": 23,
    "QB Loser": "Joe Kapp",
    "Coach Loser": "Bud Grant",
    "Loser": "Minnesota Vikings",
    "Losing Pts": 7,
    "MVP": "Len Dawson",
    "Stadium": "Tulane Stadium",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 16,
    "Referee": "",
    "Umpire": "",
    "Head Linesman": "",
    "Line Judge": "",
    "Field Judge": "",
    "Back Judge": "",
    "Side Judge": ""
  },
  {
    "Date": "17-Jan-71",
    "SB": "V ",
    "Attendance": 79204,
    "QB  Winner": "Earl Morrall , Johnny Unitas",
    "Coach Winner": "Don McCafferty",
    "Winner": "Baltimore Colts",
    "Winning Pts": 16,
    "QB Loser": "Craig Morton",
    "Coach Loser": "Tom Landry",
    "Loser": "Dallas Cowboys",
    "Losing Pts": 13,
    "MVP": "Chuck Howley",
    "Stadium": "Orange Bowl",
    "City": "Miami",
    "State": "Florida",
    "Point Difference": 3,
    "Referee": "Norm Schachter",
    "Umpire": "Paul Trepinski",
    "Head Linesman": "Ed Marion",
    "Line Judge": "Jack Fette",
    "Field Judge": "Fritz Graf",
    "Back Judge": "Hugh Gamber",
    "Side Judge": ""
  },
  {
    "Date": "16-Jan-72",
    "SB": "VI ",
    "Attendance": 81023,
    "QB  Winner": "Roger Staubach",
    "Coach Winner": "Tom Landry",
    "Winner": "Dallas Cowboys",
    "Winning Pts": 24,
    "QB Loser": "Bob Griese",
    "Coach Loser": "Don Shula",
    "Loser": "Miami Dolphins",
    "Losing Pts": 3,
    "MVP": "Roger Staubach",
    "Stadium": "Tulane Stadium",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 21,
    "Referee": "Jim Tunney",
    "Umpire": "Joe Connell",
    "Head Linesman": "Al Sabato",
    "Line Judge": "Art Holst",
    "Field Judge": "Bob Wortman",
    "Back Judge": "Ralph Vandenberg",
    "Side Judge": ""
  },
  {
    "Date": "14-Jan-73",
    "SB": "VII ",
    "Attendance": 90182,
    "QB  Winner": "Bob Griese",
    "Coach Winner": "Don Shula",
    "Winner": "Miami Dolphins",
    "Winning Pts": 14,
    "QB Loser": "Bill Kilmer",
    "Coach Loser": "George Allen",
    "Loser": "Washington Redskins",
    "Losing Pts": 7,
    "MVP": "Jake Scott",
    "Stadium": "Memorial Coliseum",
    "City": "Los Angeles",
    "State": "California",
    "Point Difference": 7,
    "Referee": "Tom Bell",
    "Umpire": "Lou Palazzi",
    "Head Linesman": "Tony Veteri",
    "Line Judge": "Bruce Alford",
    "Field Judge": "Tony Skover",
    "Back Judge": "Tom Kelleher",
    "Side Judge": ""
  },
  {
    "Date": "13-Jan-74",
    "SB": "VIII ",
    "Attendance": 71882,
    "QB  Winner": "Bob Griese",
    "Coach Winner": "Don Shula",
    "Winner": "Miami Dolphins",
    "Winning Pts": 24,
    "QB Loser": "Fran Tarkenton",
    "Coach Loser": "Bud Grant",
    "Loser": "Minnesota Vikings",
    "Losing Pts": 7,
    "MVP": "Larry Csonka",
    "Stadium": "Rice Stadium",
    "City": "Houston",
    "State": "Texas",
    "Point Difference": 17,
    "Referee": "Ben Dreith",
    "Umpire": "Ralph Morcroft",
    "Head Linesman": "Leo Miles",
    "Line Judge": "Jack Fette",
    "Field Judge": "Fritz Graf",
    "Back Judge": "Stan Javie",
    "Side Judge": ""
  },
  {
    "Date": "12-Jan-75",
    "SB": "IX ",
    "Attendance": 80997,
    "QB  Winner": "Terry Bradshaw",
    "Coach Winner": "Chuck Noll",
    "Winner": "Pittsburgh Steelers",
    "Winning Pts": 16,
    "QB Loser": "Fran Tarkenton",
    "Coach Loser": "Bud Grant",
    "Loser": "Minnesota Vikings",
    "Losing Pts": 6,
    "MVP": "Franco Harris",
    "Stadium": "Tulane Stadium",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 10,
    "Referee": "Bernie Ulman",
    "Umpire": "Al Conway",
    "Head Linesman": "Ed Marion",
    "Line Judge": "Bruce Alford",
    "Field Judge": "Dick Dolack",
    "Back Judge": "Ray Douglas",
    "Side Judge": ""
  },
  {
    "Date": "18-Jan-76",
    "SB": "X ",
    "Attendance": 80187,
    "QB  Winner": "Terry Bradshaw",
    "Coach Winner": "Chuck Noll",
    "Winner": "Pittsburgh Steelers",
    "Winning Pts": 21,
    "QB Loser": "Roger Staubach",
    "Coach Loser": "Tom Landry",
    "Loser": "Dallas Cowboys",
    "Losing Pts": 17,
    "MVP": "Lynn Swann",
    "Stadium": "Orange Bowl",
    "City": "Miami",
    "State": "Florida",
    "Point Difference": 4,
    "Referee": "Norm Schachter",
    "Umpire": "Joe Connell",
    "Head Linesman": "Leo Miles",
    "Line Judge": "Jack Fette",
    "Field Judge": "Bill O'Brien",
    "Back Judge": "Stan Javie",
    "Side Judge": ""
  },
  {
    "Date": "9-Jan-77",
    "SB": "XI ",
    "Attendance": 103438,
    "QB  Winner": "Kenny Stabler",
    "Coach Winner": "John Madden",
    "Winner": "Oakland Raiders",
    "Winning Pts": 32,
    "QB Loser": "Fran Tarkenton",
    "Coach Loser": "Bud Grant",
    "Loser": "Minnesota Vikings",
    "Losing Pts": 14,
    "MVP": "Fred Biletnikoff",
    "Stadium": "Rose Bowl",
    "City": "Pasadena",
    "State": "California",
    "Point Difference": 18,
    "Referee": "Jim Tunney",
    "Umpire": "Lou Palazzi",
    "Head Linesman": "Ed Marion",
    "Line Judge": "Bill Swanson",
    "Field Judge": "Armen Terzian",
    "Back Judge": "Tom Kelleher",
    "Side Judge": ""
  },
  {
    "Date": "15-Jan-78",
    "SB": "XII ",
    "Attendance": 76400,
    "QB  Winner": "Roger Staubach",
    "Coach Winner": "Tom Landry",
    "Winner": "Dallas Cowboys",
    "Winning Pts": 27,
    "QB Loser": "Craig Morton",
    "Coach Loser": "Red Miller",
    "Loser": "Denver Broncos",
    "Losing Pts": 10,
    "MVP": "Harvey Martin, Randy White",
    "Stadium": "Superdome",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 17,
    "Referee": "Jim Tunney",
    "Umpire": "Joe Connell",
    "Head Linesman": "Tony Veteri",
    "Line Judge": "Art Holst",
    "Field Judge": "Bob Wortman",
    "Back Judge": "Ray Douglas",
    "Side Judge": ""
  },
  {
    "Date": "21-Jan-79",
    "SB": "XIII ",
    "Attendance": 79484,
    "QB  Winner": "Terry Bradshaw",
    "Coach Winner": "Chuck Noll",
    "Winner": "Pittsburgh Steelers",
    "Winning Pts": 35,
    "QB Loser": "Roger Staubach",
    "Coach Loser": "Tom Landry",
    "Loser": "Dallas Cowboys",
    "Losing Pts": 31,
    "MVP": "Terry Bradshaw",
    "Stadium": "Orange Bowl",
    "City": "Miami",
    "State": "Florida",
    "Point Difference": 4,
    "Referee": "Pat Haggerty",
    "Umpire": "Art Demmas",
    "Head Linesman": "Jerry Bergman",
    "Line Judge": "Jack Fette",
    "Field Judge": "Fred Swearingen",
    "Back Judge": "Pat Knight",
    "Side Judge": "Dean Look"
  },
  {
    "Date": "20-Jan-80",
    "SB": "XIV ",
    "Attendance": 103985,
    "QB  Winner": "Terry Bradshaw",
    "Coach Winner": "Chuck Noll",
    "Winner": "Pittsburgh Steelers",
    "Winning Pts": 31,
    "QB Loser": "Vince Ferragamo",
    "Coach Loser": "Ray Malavasi",
    "Loser": "Los Angeles Rams",
    "Losing Pts": 19,
    "MVP": "Terry Bradshaw",
    "Stadium": "Rose Bowl",
    "City": "Pasadena",
    "State": "California",
    "Point Difference": 12,
    "Referee": "Fred Silva",
    "Umpire": "Al Conway",
    "Head Linesman": "Burl Toler",
    "Line Judge": "Bob Beeks",
    "Field Judge": "Charley Musser",
    "Back Judge": "Stan Javie",
    "Side Judge": "Ben Tompkins"
  },
  {
    "Date": "25-Jan-81",
    "SB": "XV ",
    "Attendance": 76135,
    "QB  Winner": "Jim Plunkett",
    "Coach Winner": "Tom Flores",
    "Winner": "Oakland Raiders",
    "Winning Pts": 27,
    "QB Loser": "Ron Jaworski",
    "Coach Loser": "Dick Vermeil",
    "Loser": "Philadelphia Eagles",
    "Losing Pts": 10,
    "MVP": "Jim Plunkett",
    "Stadium": "Louisiana Superdome",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 17,
    "Referee": "Ben Dreith",
    "Umpire": "Frank Sinkovitz",
    "Head Linesman": "Tony Veteri",
    "Line Judge": "Tom Dooley",
    "Field Judge": "Fritz Graf",
    "Back Judge": "Tom Kelleher",
    "Side Judge": "Dean Look"
  },
  {
    "Date": "24-Jan-82",
    "SB": "XVI ",
    "Attendance": 81270,
    "QB  Winner": "Joe Montana",
    "Coach Winner": "Bill Walsh",
    "Winner": "San Francisco 49ers",
    "Winning Pts": 26,
    "QB Loser": "Ken Anderson",
    "Coach Loser": "Forrest Gregg",
    "Loser": "Cincinnati Bengals",
    "Losing Pts": 21,
    "MVP": "Joe Montana",
    "Stadium": "Pontiac Silverdome",
    "City": "Pontiac",
    "State": "Michigan",
    "Point Difference": 5,
    "Referee": "Pat Haggerty",
    "Umpire": "Al Conway",
    "Head Linesman": "Jerry Bergman",
    "Line Judge": "Bob Beeks",
    "Field Judge": "Don Hakes",
    "Back Judge": "Bill Swanson",
    "Side Judge": "Bob Rice"
  },
  {
    "Date": "30-Jan-83",
    "SB": "XVII ",
    "Attendance": 103667,
    "QB  Winner": "Joe Theismann",
    "Coach Winner": "Joe Gibbs",
    "Winner": "Washington Redskins",
    "Winning Pts": 27,
    "QB Loser": "David Woodley",
    "Coach Loser": "Don Shula",
    "Loser": "Miami Dolphins",
    "Losing Pts": 17,
    "MVP": "John Riggins",
    "Stadium": "Rose Bowl",
    "City": "Pasadena",
    "State": "California",
    "Point Difference": 10,
    "Referee": "Jerry Markbreit",
    "Umpire": "Art Demmas",
    "Head Linesman": "Dale Hamer",
    "Line Judge": "Bill Reynolds",
    "Field Judge": "Don Orr",
    "Back Judge": "Dick Hantak",
    "Side Judge": "Dave Parry"
  },
  {
    "Date": "22-Jan-84",
    "SB": "XVIII ",
    "Attendance": 72920,
    "QB  Winner": "Jim Plunkett",
    "Coach Winner": "Tom Flores",
    "Winner": "Los Angeles Raiders",
    "Winning Pts": 38,
    "QB Loser": "Joe Theismann",
    "Coach Loser": "Joe Gibbs",
    "Loser": "Washington Redskins",
    "Losing Pts": 9,
    "MVP": "Marcus Allen",
    "Stadium": "Tampa Stadium",
    "City": "Tampa",
    "State": "Florida",
    "Point Difference": 29,
    "Referee": "Gene Barth",
    "Umpire": "Gordon Wells",
    "Head Linesman": "Jerry Bergman",
    "Line Judge": "Bob Beeks",
    "Field Judge": "Fritz Graf",
    "Back Judge": "Gil Mace",
    "Side Judge": "Ben Tompkins"
  },
  {
    "Date": "20-Jan-85",
    "SB": "XIX ",
    "Attendance": 84059,
    "QB  Winner": "Joe Montano",
    "Coach Winner": "Bill Walsh",
    "Winner": "San Francisco 49ers",
    "Winning Pts": 38,
    "QB Loser": "Dan Marino",
    "Coach Loser": "Don Shula",
    "Loser": "Miami Dolphins",
    "Losing Pts": 16,
    "MVP": "Joe Montana",
    "Stadium": "Stanford Stadium",
    "City": "Palo Alto",
    "State": "California",
    "Point Difference": 22,
    "Referee": "Pat Haggerty",
    "Umpire": "Tom Hensley",
    "Head Linesman": "Leo Miles",
    "Line Judge": "Ray Dodez",
    "Field Judge": "Bob Lewis",
    "Back Judge": "Tom Kelleher",
    "Side Judge": "Bill Quinby"
  },
  {
    "Date": "26-Jan-86",
    "SB": "XX ",
    "Attendance": 73818,
    "QB  Winner": "Jim McMahon",
    "Coach Winner": "Mike Ditka",
    "Winner": "Chicago Bears",
    "Winning Pts": 46,
    "QB Loser": "Tony Eason, Steve Grogan",
    "Coach Loser": "Raymond Berry",
    "Loser": "New England Patriots",
    "Losing Pts": 10,
    "MVP": "Richard Dent",
    "Stadium": "Louisiana Superdome",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 36,
    "Referee": "Red Cashion",
    "Umpire": "Ron Botchan",
    "Head Linesman": "Dale Williams",
    "Line Judge": "Bama Glass",
    "Field Judge": "Jack Vaughan",
    "Back Judge": "Al Jury",
    "Side Judge": "Bob Rice"
  },
  {
    "Date": "25-Jan-87",
    "SB": "XXI ",
    "Attendance": 101063,
    "QB  Winner": "Phil Simms",
    "Coach Winner": "Bill Parcells",
    "Winner": "New York Giants",
    "Winning Pts": 39,
    "QB Loser": "John Elway",
    "Coach Loser": "Dan Reeves",
    "Loser": "Denver Broncos",
    "Losing Pts": 20,
    "MVP": "Phil Simms",
    "Stadium": "Rose Bowl",
    "City": "Pasadena",
    "State": "California",
    "Point Difference": 19,
    "Referee": "Jerry Markbreit",
    "Umpire": "Bob Boylston",
    "Head Linesman": "Terry Gierke",
    "Line Judge": "Bob Beeks",
    "Field Judge": "Pat Mallette",
    "Back Judge": "Jim Poole",
    "Side Judge": "Gil Mace"
  },
  {
    "Date": "31-Jan-88",
    "SB": "XXII ",
    "Attendance": 73302,
    "QB  Winner": "Doug Williams",
    "Coach Winner": "Joe Gibbs ",
    "Winner": "Washington Redskins",
    "Winning Pts": 42,
    "QB Loser": "John Elway",
    "Coach Loser": "Dan Reeves ",
    "Loser": "Denver Broncos",
    "Losing Pts": 10,
    "MVP": "Doug Williams",
    "Stadium": "Jack Murphy Stadium",
    "City": "San Diego",
    "State": "California",
    "Point Difference": 32,
    "Referee": "Bob McElwee",
    "Umpire": "Al Conway",
    "Head Linesman": "Dale Hamer",
    "Line Judge": "Jack Fette",
    "Field Judge": "Johnny Grier",
    "Back Judge": "Al Jury",
    "Side Judge": "Don Wedge"
  },
  {
    "Date": "22-Jan-89",
    "SB": "XXIII ",
    "Attendance": 75129,
    "QB  Winner": "Joe Montana",
    "Coach Winner": "Bill Walsh ",
    "Winner": "San Francisco 49ers",
    "Winning Pts": 20,
    "QB Loser": "Boomer Esiason",
    "Coach Loser": "Sam Wyche",
    "Loser": "Cincinnati Bengals",
    "Losing Pts": 16,
    "MVP": "Jerry Rice",
    "Stadium": "Joe Robbie Stadium",
    "City": "Miami Gardens",
    "State": "Florida",
    "Point Difference": 4,
    "Referee": "Jerry Seeman",
    "Umpire": "Gordon Wells",
    "Head Linesman": "Jerry Bergman",
    "Line Judge": "Bob Beeks",
    "Field Judge": "Bobby Skelton",
    "Back Judge": "Paul Baetz",
    "Side Judge": "Gary Lane"
  },
  {
    "Date": "28-Jan-90",
    "SB": "XXIV ",
    "Attendance": 72919,
    "QB  Winner": "Joe Montana",
    "Coach Winner": "George Seifert",
    "Winner": "San Francisco 49ers",
    "Winning Pts": 55,
    "QB Loser": "John Elway",
    "Coach Loser": "Dan Reeves ",
    "Loser": "Denver Broncos",
    "Losing Pts": 10,
    "MVP": "Joe Montana",
    "Stadium": "Louisiana Superdome",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 45,
    "Referee": "Dick Jorgensen",
    "Umpire": "Hendi Ancich",
    "Head Linesman": "Earnie Frantz",
    "Line Judge": "Ron Blum",
    "Field Judge": "Don Orr",
    "Back Judge": "Al Jury",
    "Side Judge": "Gerald Austin"
  },
  {
    "Date": "27-Jan-91",
    "SB": "XXV ",
    "Attendance": 73813,
    "QB  Winner": "Jeff Hostetler",
    "Coach Winner": "Bill Parcells ",
    "Winner": "New York Giants",
    "Winning Pts": 20,
    "QB Loser": "Jim Kelly",
    "Coach Loser": "Marv Levy",
    "Loser": "Buffalo Bills",
    "Losing Pts": 19,
    "MVP": "Ottis Anderson",
    "Stadium": "Tampa Stadium",
    "City": "Tampa",
    "State": "Florida",
    "Point Difference": 1,
    "Referee": "Jerry Seeman",
    "Umpire": "Art Demmas",
    "Head Linesman": "Sid Semon",
    "Line Judge": "Dick McKenzie",
    "Field Judge": "Jack Vaughan",
    "Back Judge": "Banks Williams",
    "Side Judge": "Larry Nemmers"
  },
  {
    "Date": "26-Jan-92",
    "SB": "XXVI ",
    "Attendance": 63130,
    "QB  Winner": "Mark Rypien",
    "Coach Winner": "Joe Gibbs ",
    "Winner": "Washington Redskins",
    "Winning Pts": 37,
    "QB Loser": "Jim Kelly",
    "Coach Loser": "Marv Levy ",
    "Loser": "Buffalo Bills",
    "Losing Pts": 24,
    "MVP": "Mark Rypien",
    "Stadium": "Metrodome",
    "City": "Minneapolis",
    "State": "Minnesota",
    "Point Difference": 13,
    "Referee": "Jerry Markbreit",
    "Umpire": "Bob Boylston",
    "Head Linesman": "Dale Williams",
    "Line Judge": "Ron Blum",
    "Field Judge": "Ed Merrifield",
    "Back Judge": "Paul Baetz",
    "Side Judge": "Dick Creed"
  },
  {
    "Date": "31-Jan-93",
    "SB": "XXVII ",
    "Attendance": 98374,
    "QB  Winner": "Troy Aikman",
    "Coach Winner": "Jimmy Johnson",
    "Winner": "Dallas Cowboys",
    "Winning Pts": 52,
    "QB Loser": "Jim Kelly, Frank Reich",
    "Coach Loser": "Marv Levy ",
    "Loser": "Buffalo Bills",
    "Losing Pts": 17,
    "MVP": "Troy Aikman",
    "Stadium": "Rose Bowl",
    "City": "Pasadena",
    "State": "California",
    "Point Difference": 35,
    "Referee": "Dick Hantak",
    "Umpire": "Ron Botchan",
    "Head Linesman": "Ron Phares",
    "Line Judge": "Dick McKenzie",
    "Field Judge": "Donnie Hampton",
    "Back Judge": "Jim Poole",
    "Side Judge": "Dean Look"
  },
  {
    "Date": "30-Jan-94",
    "SB": "XXVIII ",
    "Attendance": 72817,
    "QB  Winner": "Troy Aikman",
    "Coach Winner": "Jimmy Johnson ",
    "Winner": "Dallas Cowboys",
    "Winning Pts": 30,
    "QB Loser": "Jim Kelly",
    "Coach Loser": "Marv Levy ",
    "Loser": "Buffalo Bills",
    "Losing Pts": 13,
    "MVP": "Emmitt Smith",
    "Stadium": "Georgia Dome",
    "City": "Atlanta",
    "State": "Georgia",
    "Point Difference": 17,
    "Referee": "Bob McElwee",
    "Umpire": "Art Demmas",
    "Head Linesman": "Sid Semon",
    "Line Judge": "Tom Barnes",
    "Field Judge": "Don Orr",
    "Back Judge": "Al Jury",
    "Side Judge": "Nate Jones"
  },
  {
    "Date": "29-Jan-95",
    "SB": "XXIX ",
    "Attendance": 74107,
    "QB  Winner": "Steve Young",
    "Coach Winner": "George Seifert ",
    "Winner": "San Francisco 49ers",
    "Winning Pts": 49,
    "QB Loser": "Stan Humphreys",
    "Coach Loser": "Bobby Ross",
    "Loser": "San Diego Chargers",
    "Losing Pts": 26,
    "MVP": "Steve Young",
    "Stadium": "Joe Robbie Stadium",
    "City": "Miami Gardens",
    "State": "Florida",
    "Point Difference": 23,
    "Referee": "Jerry Markbreit",
    "Umpire": "Ron Botchan",
    "Head Linesman": "Ron Phares",
    "Line Judge": "Ron Baynes",
    "Field Judge": "Jack Vaughan",
    "Back Judge": "Tim Millis",
    "Side Judge": "Tom Fincken"
  },
  {
    "Date": "28-Jan-96",
    "SB": "XXX ",
    "Attendance": 76347,
    "QB  Winner": "Troy Aikman",
    "Coach Winner": "Barry Switzer",
    "Winner": "Dallas Cowboys",
    "Winning Pts": 27,
    "QB Loser": "Neil O'Donnell",
    "Coach Loser": "Bill Cowher",
    "Loser": "Pittsburgh Steelers",
    "Losing Pts": 17,
    "MVP": "Larry Brown",
    "Stadium": "Sun Devil Stadium",
    "City": "Tempe",
    "State": "Arizona",
    "Point Difference": 10,
    "Referee": "Red Cashion",
    "Umpire": "John Keck",
    "Head Linesman": "Paul Weidner",
    "Line Judge": "Dale Orem",
    "Field Judge": "Don Hakes",
    "Back Judge": "Dick Creed",
    "Side Judge": "Bill Carollo"
  },
  {
    "Date": "26-Jan-97",
    "SB": "XXXI ",
    "Attendance": 72301,
    "QB  Winner": "Brett Favre",
    "Coach Winner": "Mike Holmgren",
    "Winner": "Green Bay Packers",
    "Winning Pts": 35,
    "QB Loser": "Drew Bledsoe",
    "Coach Loser": "Bill Parcells",
    "Loser": "New England Patriots",
    "Losing Pts": 21,
    "MVP": "Desmond Howard",
    "Stadium": "Louisiana Superdome",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 14,
    "Referee": "Gerald Austin",
    "Umpire": "Ron Botchan",
    "Head Linesman": "Earnie Frantz",
    "Line Judge": "Jeff Bergman",
    "Field Judge": "Phil Luckett",
    "Back Judge": "Scott Steenson",
    "Side Judge": "Tom Fincken"
  },
  {
    "Date": "25-Jan-98",
    "SB": "XXXII ",
    "Attendance": 68912,
    "QB  Winner": "John Elway",
    "Coach Winner": "Mike Shanahan",
    "Winner": "Denver Broncos",
    "Winning Pts": 31,
    "QB Loser": "Brett Favre",
    "Coach Loser": "Mike Holmgren",
    "Loser": "Green Bay Packers",
    "Losing Pts": 24,
    "MVP": "Terrell Davis",
    "Stadium": "Qualcomm Stadium",
    "City": "San Diego",
    "State": "California",
    "Point Difference": 7,
    "Referee": "Ed Hochuli",
    "Umpire": "Jim Quirk",
    "Head Linesman": "John Schleyer",
    "Line Judge": "Ben Montgomery",
    "Field Judge": "Don Dorkowski",
    "Back Judge": "Paul Baetz",
    "Side Judge": "Doug Toole"
  },
  {
    "Date": "31-Jan-99",
    "SB": "XXXIII ",
    "Attendance": 74803,
    "QB  Winner": "John Elway",
    "Coach Winner": "Mike Shanahan ",
    "Winner": "Denver Broncos",
    "Winning Pts": 34,
    "QB Loser": "Chris Chandler",
    "Coach Loser": "Dan Reeves ",
    "Loser": "Atlanta Falcons",
    "Losing Pts": 19,
    "MVP": "John Elway",
    "Stadium": "Pro Player Stadium",
    "City": "Miami Gardens",
    "State": "Florida",
    "Point Difference": 15,
    "Referee": "Bernie Kukar",
    "Umpire": "Jim Daopoulos",
    "Head Linesman": "Sanford Rivers",
    "Line Judge": "Ron Baynes",
    "Field Judge": "Tim Millis",
    "Back Judge": "Don Hakes",
    "Side Judge": "Gary Lane"
  },
  {
    "Date": "30-Jan-00",
    "SB": "XXXIV ",
    "Attendance": 72625,
    "QB  Winner": "Kurt Warner",
    "Coach Winner": "Dick Vermeil",
    "Winner": "St. Louis Rams",
    "Winning Pts": 23,
    "QB Loser": "Steve McNair",
    "Coach Loser": "Jeff Fisher",
    "Loser": "Tennessee Titans",
    "Losing Pts": 16,
    "MVP": "Kurt Warner",
    "Stadium": "Georgia Dome",
    "City": "Atlanta",
    "State": "Georgia",
    "Point Difference": 7,
    "Referee": "Bob McElwee",
    "Umpire": "Ron Botchan",
    "Head Linesman": "Earnie Frantz",
    "Line Judge": "Byron Boston",
    "Field Judge": "Al Jury",
    "Back Judge": "Bill Leavy",
    "Side Judge": "Tom Fincken"
  },
  {
    "Date": "28-Jan-01",
    "SB": "XXXV ",
    "Attendance": 71921,
    "QB  Winner": "Trent Dilfer",
    "Coach Winner": "Brian Billick",
    "Winner": "Baltimore Ravens",
    "Winning Pts": 34,
    "QB Loser": "Kerry Collins",
    "Coach Loser": "Jim Fassel",
    "Loser": "New York Giants",
    "Losing Pts": 7,
    "MVP": "Ray Lewis",
    "Stadium": "Raymond James Stadium",
    "City": "Tampa",
    "State": "Florida",
    "Point Difference": 27,
    "Referee": "Gerald Austin",
    "Umpire": "Chad Brown",
    "Head Linesman": "Tony Veteri, Jr.",
    "Line Judge": "Walt Anderson",
    "Field Judge": "Bill Lovett",
    "Back Judge": "Bill Schmitz",
    "Side Judge": "Doug Toole"
  },
  {
    "Date": "3-Feb-02",
    "SB": "XXXVI ",
    "Attendance": 72922,
    "QB  Winner": "Tom Brady",
    "Coach Winner": "Bill Belichick",
    "Winner": "New England Patriots",
    "Winning Pts": 20,
    "QB Loser": "Kurt Warner",
    "Coach Loser": "Mike Martz",
    "Loser": "St. Louis Rams",
    "Losing Pts": 17,
    "MVP": "Tom Brady",
    "Stadium": "Louisiana Superdome",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 3,
    "Referee": "Bernie Kukar",
    "Umpire": "Jeff Rice",
    "Head Linesman": "Mark Hittner",
    "Line Judge": "Ron Phares",
    "Field Judge": "Pete Morelli",
    "Back Judge": "Scott Green",
    "Side Judge": "Laird Hayes"
  },
  {
    "Date": "26-Jan-03",
    "SB": "XXXVII ",
    "Attendance": 67603,
    "QB  Winner": "Brad Johnson",
    "Coach Winner": "Jon Gruden",
    "Winner": "Tampa Bay Buccaneers",
    "Winning Pts": 48,
    "QB Loser": "Rich Gannon",
    "Coach Loser": "Bill Callahan",
    "Loser": "Oakland Raiders",
    "Losing Pts": 21,
    "MVP": "Dexter Jackson",
    "Stadium": "Qualcomm Stadium",
    "City": "San Diego",
    "State": "California",
    "Point Difference": 27,
    "Referee": "Bill Carollo",
    "Umpire": "Ed Coukart",
    "Head Linesman": "Dale Williams",
    "Line Judge": "Mark Steinkerchner",
    "Field Judge": "Tom Sifferman",
    "Back Judge": "Don Carey",
    "Side Judge": "Rick Patterson"
  },
  {
    "Date": "1-Feb-04",
    "SB": "XXXVIII ",
    "Attendance": 71525,
    "QB  Winner": "Tom Brady",
    "Coach Winner": "Bill Belichick ",
    "Winner": "New England Patriots",
    "Winning Pts": 32,
    "QB Loser": "Jake Delhomme",
    "Coach Loser": "John Fox",
    "Loser": "Carolina Panthers",
    "Losing Pts": 29,
    "MVP": "Tom Brady",
    "Stadium": "Reliant Stadium",
    "City": "Houston",
    "State": "Texas",
    "Point Difference": 3,
    "Referee": "Ed Hochuli",
    "Umpire": "Jeff Rice",
    "Head Linesman": "Mark Hittner",
    "Line Judge": "Ben Montgomery",
    "Field Judge": "Tom Sifferman",
    "Back Judge": "Scott Green",
    "Side Judge": "Laird Hayes"
  },
  {
    "Date": "6-Feb-05",
    "SB": "XXXIX ",
    "Attendance": 78125,
    "QB  Winner": "Tom Brady",
    "Coach Winner": "Bill Belichick ",
    "Winner": "New England Patriots",
    "Winning Pts": 24,
    "QB Loser": "Donovan McNabb",
    "Coach Loser": "Andy Reid",
    "Loser": "Philadelphia Eagles",
    "Losing Pts": 21,
    "MVP": "Deion Branch",
    "Stadium": "Alltel Stadium",
    "City": "Jacksonville",
    "State": "Florida",
    "Point Difference": 3,
    "Referee": "Terry McAulay",
    "Umpire": "Carl Paganelli",
    "Head Linesman": "Gary Slaughter",
    "Line Judge": "Mark Steinkerchner",
    "Field Judge": "Tom Sifferman",
    "Back Judge": "Tony Steratore",
    "Side Judge": "Rick Patterson"
  },
  {
    "Date": "5-Feb-06",
    "SB": "XL ",
    "Attendance": 68206,
    "QB  Winner": "Ben Roethlisberger",
    "Coach Winner": "Bill Cowher",
    "Winner": "Pittsburgh Steelers",
    "Winning Pts": 21,
    "QB Loser": "Matt Hasselbeck",
    "Coach Loser": "Mike Holmgren ",
    "Loser": "Seattle Seahawks",
    "Losing Pts": 10,
    "MVP": "Hines Ward",
    "Stadium": "Ford Field",
    "City": "Detroit",
    "State": "Michigan",
    "Point Difference": 11,
    "Referee": "Bill Leavy",
    "Umpire": "Garth DeFelice",
    "Head Linesman": "Mark Hittner",
    "Line Judge": "Mark Perlman",
    "Field Judge": "Steve Zimmer",
    "Back Judge": "Bob Waggoner",
    "Side Judge": "Tom Hill"
  },
  {
    "Date": "4-Feb-07",
    "SB": "XLI ",
    "Attendance": 74512,
    "QB  Winner": "Peyton Manning",
    "Coach Winner": "Tony Dungy",
    "Winner": "Indianapolis Colts",
    "Winning Pts": 29,
    "QB Loser": "Rex Grossman",
    "Coach Loser": "Lovie Smith",
    "Loser": "Chicago Bears",
    "Losing Pts": 17,
    "MVP": "Peyton Manning",
    "Stadium": "Dolphin Stadium",
    "City": "Miami Gardens",
    "State": "Florida",
    "Point Difference": 12,
    "Referee": "Tony Corrente",
    "Umpire": "Carl Paganelli",
    "Head Linesman": "George Hayward",
    "Line Judge": "Ron Marinucci",
    "Field Judge": "Jim Saracino",
    "Back Judge": "Perry Paganelli",
    "Side Judge": "John Parry"
  },
  {
    "Date": "3-Feb-08",
    "SB": "XLII ",
    "Attendance": 71101,
    "QB  Winner": "Eli Manning",
    "Coach Winner": "Tom Coughlin",
    "Winner": "New York Giants",
    "Winning Pts": 17,
    "QB Loser": "Tom Brady",
    "Coach Loser": "Bill Belichick",
    "Loser": "New England Patriots",
    "Losing Pts": 14,
    "MVP": "Eli Manning",
    "Stadium": "University of Phoenix Stadium",
    "City": "Glendale",
    "State": "Arizona",
    "Point Difference": 3,
    "Referee": "Mike Carey[3]",
    "Umpire": "Tony Michalek",
    "Head Linesman": "Gary Slaughter",
    "Line Judge": "Carl Johnson",
    "Field Judge": "Boris Cheek",
    "Back Judge": "Scott Helverson",
    "Side Judge": "Larry Rose"
  },
  {
    "Date": "1-Feb-09",
    "SB": "XLIII ",
    "Attendance": 70774,
    "QB  Winner": "Ben Roethlisberger",
    "Coach Winner": "Mike Tomlin",
    "Winner": "Pittsburgh Steelers",
    "Winning Pts": 27,
    "QB Loser": "Kurt Warner",
    "Coach Loser": "Ken Whisenhunt",
    "Loser": "Arizona Cardinals",
    "Losing Pts": 23,
    "MVP": "Santonio Holmes",
    "Stadium": "Raymond James Stadium",
    "City": "Tampa",
    "State": "Florida",
    "Point Difference": 4,
    "Referee": "Terry McAulay",
    "Umpire": "Roy Ellison",
    "Head Linesman": "Derrick Bowers",
    "Line Judge": "Mark Perlman",
    "Field Judge": "Greg Gautreaux",
    "Back Judge": "Keith Ferguson",
    "Side Judge": "Michael Banks"
  },
  {
    "Date": "7-Feb-10",
    "SB": "XLIV ",
    "Attendance": 74059,
    "QB  Winner": "Drew Brees",
    "Coach Winner": "Sean Payton",
    "Winner": "New Orleans Saints",
    "Winning Pts": 31,
    "QB Loser": "Peyton Manning",
    "Coach Loser": "Jim Caldwell",
    "Loser": "Indianapolis Colts",
    "Losing Pts": 17,
    "MVP": "Drew Brees",
    "Stadium": "Sun Life Stadium",
    "City": "Miami Gardens",
    "State": "Florida",
    "Point Difference": 14,
    "Referee": "Scott Green[4]",
    "Umpire": "Undrey Wash",
    "Head Linesman": "John McGrath",
    "Line Judge": "Jeff Seeman",
    "Field Judge": "Rob Vernatchi",
    "Back Judge": "Greg Steed",
    "Side Judge": "Greg Meyer"
  },
  {
    "Date": "6-Feb-11",
    "SB": "XLV ",
    "Attendance": 103219,
    "QB  Winner": "Aaron Rodgers",
    "Coach Winner": "Mike McCarthy",
    "Winner": "Green Bay Packers",
    "Winning Pts": 31,
    "QB Loser": "Ben Roethlisberger",
    "Coach Loser": "Mike Tomlin",
    "Loser": "Pittsburgh Steelers",
    "Losing Pts": 25,
    "MVP": "Aaron Rodgers",
    "Stadium": "Cowboys Stadium",
    "City": "Arlington",
    "State": "Texas",
    "Point Difference": 6,
    "Referee": "Walt Anderson[5]",
    "Umpire": "Chad Brown",
    "Head Linesman": "Kent Payne",
    "Line Judge": "John Hussey",
    "Field Judge": "Doug Rosenbaum",
    "Back Judge": "Scott Helverson",
    "Side Judge": "Mike Weatherford"
  },
  {
    "Date": "5-Feb-12",
    "SB": "XLVI ",
    "Attendance": 68658,
    "QB  Winner": "Eli Manning",
    "Coach Winner": "Tom Coughlin ",
    "Winner": "New York Giants",
    "Winning Pts": 21,
    "QB Loser": "Tom Brady",
    "Coach Loser": "Bill Belichick ",
    "Loser": "New England Patriots",
    "Losing Pts": 17,
    "MVP": "Eli Manning",
    "Stadium": "Lucas Oil Stadium",
    "City": "Indianapolis",
    "State": "Indiana",
    "Point Difference": 4,
    "Referee": "John Parry",
    "Umpire": "Carl Paganelli",
    "Head Linesman": "Tom Stabile",
    "Line Judge": "Gary Arthur",
    "Field Judge": "Gary Cavaletto",
    "Back Judge": "Tony Steratore",
    "Side Judge": "Laird Hayes"
  },
  {
    "Date": "3-Feb-13",
    "SB": "XLVII ",
    "Attendance": 71024,
    "QB  Winner": "Joe Flacco",
    "Coach Winner": "John Harbaugh",
    "Winner": "Baltimore Ravens",
    "Winning Pts": 34,
    "QB Loser": "Colin Kaepernick",
    "Coach Loser": "Jim Harbaugh",
    "Loser": "San Francisco 49ers",
    "Losing Pts": 31,
    "MVP": "Joe Flacco",
    "Stadium": "Mercedes-Benz Superdome",
    "City": "New Orleans",
    "State": "Louisiana",
    "Point Difference": 3,
    "Referee": "Jerome Boger",
    "Umpire": "Darrell Jenkins",
    "Head Linesman": "Steve Stelljes",
    "Line Judge": "Byron Boston",
    "Field Judge": "Craig Wrolstad",
    "Back Judge": "Dino Paganelli",
    "Side Judge": "Joe Larrew"
  },
  {
    "Date": "2-Feb-14",
    "SB": "XLVIII ",
    "Attendance": 82529,
    "QB  Winner": "Russell Wilson",
    "Coach Winner": "Pete Carroll",
    "Winner": "Seattle Seahawks",
    "Winning Pts": 43,
    "QB Loser": "Peyton Manning",
    "Coach Loser": "John Fox ",
    "Loser": "Denver Broncos",
    "Losing Pts": 8,
    "MVP": "Malcolm Smith",
    "Stadium": "MetLife Stadium",
    "City": "East Rutherford",
    "State": "New Jersey",
    "Point Difference": 35,
    "Referee": "Terry McAulay",
    "Umpire": "Carl Paganelli",
    "Head Linesman": "Jim Mello",
    "Line Judge": "Tom Symonette",
    "Field Judge": "Scott Steenson",
    "Back Judge": "Steve Freeman",
    "Side Judge": "Dave Wyant"
  },
  {
    "Date": "1-Feb-15",
    "SB": "XLIX ",
    "Attendance": 70288,
    "QB  Winner": "Tom Brady",
    "Coach Winner": "Bill Belichick ",
    "Winner": "New England Patriots",
    "Winning Pts": 28,
    "QB Loser": "Russell Wilson",
    "Coach Loser": "Pete Carroll",
    "Loser": "Seattle Seahawks",
    "Losing Pts": 24,
    "MVP": "Tom Brady",
    "Stadium": "University of Phoenix Stadium",
    "City": "Glendale",
    "State": "Arizona",
    "Point Difference": 4,
    "Referee": "Bill Vinovich",
    "Umpire": "Bill Schuster",
    "Head Linesman": "Dana McKenzie",
    "Line Judge": "Mark Perlman",
    "Field Judge": "Bob Waggoner",
    "Back Judge": "Terrence Miles",
    "Side Judge": "Tom Hill"
  },
  {
    "Date": "7-Feb-16",
    "SB": "L",
    "Attendance": 71088,
    "QB  Winner": "Peyton Manning",
    "Coach Winner": "Gary Kubiak",
    "Winner": "Denver Broncos",
    "Winning Pts": 24,
    "QB Loser": "Cam Newton",
    "Coach Loser": "Ron Rivera",
    "Loser": "Carolina Panthers",
    "Losing Pts": 10,
    "MVP": "Von Miller",
    "Stadium": "Levi's Stadium",
    "City": "Santa Clara",
    "State": "California",
    "Point Difference": 14,
    "Referee": "Clete Blakeman",
    "Umpire": "Jeff Rice",
    "Head Linesman": "Wayne Mackie",
    "Line Judge": "Rusty Baynes",
    "Field Judge": "Boris Cheek",
    "Back Judge": "Keith Ferguson",
    "Side Judge": "Scott Edwards"
  },
  {
    "Date": "5-Feb-17",
    "SB": "LI",
    "Attendance": "",
    "QB  Winner": "",
    "Coach Winner": "",
    "Winner": "",
    "Winning Pts": "",
    "QB Loser": "",
    "Coach Loser": "",
    "Loser": "",
    "Losing Pts": "",
    "MVP": "",
    "Stadium": "NRG Stadium",
    "City": "Houston",
    "State": "Texas",
    "Point Difference": "",
    "Referee": "Carl Cheffers",
    "Umpire": "Dan Ferrell",
    "Head Linesman": "Kent Payne",
    "Line Judge": "Jeff Seeman",
    "Field Judge": "Doug Rosenbaum",
    "Back Judge": "Todd Prukop",
    "Side Judge": "Dyrol Prioleau"
  },
]