export default [
  {
    "2020": "Governments successfully use social media to engage citizens. Social media provides constant stream of localised data for governments to analyse sentiment & track the effectiveness of their services.",
    "2030": "Governments build platforms, hold partners accountable, manage crowdsourced campaigns etc.",
    "2050": "Operational shortcomings addressed using tech and citizen input. One online space for all services, and one physical space in each locale, streamlines govt.",
    "Innovation / Development": "Government.io",
    "Category": "Governance",
    "buzz (google index)": "149,000",
    "type": "innovation",
    "now": "Governments attempt to use social media to engage citizens.",
    "line between 2020 & 2030": "Beta Government. Policy makers apply the 'agile software development model' to policy. Prototypes, pilots, trials, etc.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, TheVerge, KMPG",
    "URL": ""
  },
  {
    "2020": "Government encourages 'triple-bottom line' businesses - focus on social and environmental goals in addition to financial ones. Multi-trillion-dollar capital markets emerge for social outcomes",
    "2030": "Triple Sector Democracy. Citizens work at solving problems through social, mobile and cloud tech, e.g. micro-tasking, peer-to-peer models.",
    "2050": "",
    "Innovation / Development": "Triple Bottom Line",
    "Category": "Governance",
    "buzz (google index)": "1,420,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Triple Sector State. Government, business, citizens collaborate to shape the state.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Government works with NGOs, corporations, social enterprises and citizens - and other non-state problem solvers.",
    "2030": "Physical and online innovation spaces - government works with citizens and companies to come up with new ideas.  Governments use crowdsourcing to gain broader input when drafting policy.",
    "2050": "Demarchy: rulers are randomly chosen from a pool of selected decision-makers. Term coined by philosopher John Burnheim",
    "Innovation / Development": "Collaborative governance",
    "Category": "Governance",
    "buzz (google index)": "263,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Reduced, optimised civil service attracts top talent. Return of parastatals, linking of political will & private resources.",
    "beyond": "Government allows cities a more active & empowered role - more funding & more authority.",
    "": "",
    "Source": "Deloitte, J. Burnheim, WEC, McKinsey, KMPG",
    "URL": ""
  },
  {
    "2020": "Big data improves tracking of performance and outcomes, allowing regulators to focus more on achieving goals and less on processes.",
    "2030": "Preemptive Government. Data used to generate predictive models for government. Resources shifted from reaction to prevention.",
    "2050": "Cyberocracy: emphasises symbolic, cultural, psychological aspects of policymaking. Information unbound, unchannelled. Eventually leads to AI civil service, or even AI head of state.",
    "Innovation / Development": "Data-driven policy",
    "Category": "Governance",
    "buzz (google index)": 37300,
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Advanced algorithms provide rich, live data that informs government decision-making.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Staffing cloud. Permanent employees act as consultants. Flexible teams formed to focus on specific projects.",
    "2030": "Governments work with citizens to address challenges, e.g. climate change.",
    "2050": "Noocracy: government of the wise, global brain, 'syntellect', hive-mind. Stems from Plato's 'government of the wise' concept. Popularised by Vladimir Vernadsky.",
    "Innovation / Development": "Citizen-consumers",
    "Category": "Governance",
    "buzz (google index)": 41900,
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Co-creation means people are more invested in government, and engagement increases. New opportunities for national and global problem solving through mass collaboration on vast data sets.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Vladimir Vernadsky",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "Cloud States. Extra-territorial initiatives, cross-border connectivity. State boundaries blurred & dissolve as interaction, debate and creation spans borders.",
    "Innovation / Development": "Cloud States",
    "Category": "Governance",
    "buzz (google index)": "",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Collaborative Cloud. Interactive cloud platforms faciliate engagement by citizen-consumers.",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "Targeted transparency. Public demands government and corporate disclosure. Easily-accessible data is made available.",
    "2030": "Radical transparency becomes the norm.",
    "2050": "",
    "Innovation / Development": "Data Transparency",
    "Category": "Governance",
    "buzz (google index)": "381,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "Radical transparency becomes the law",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Government faces challenges in delivering public services - reaching both the hyper-connected and the poor, elderly, deeply rural segments who aren't connected.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Digital divide",
    "Category": "Governance",
    "buzz (google index)": "4,670,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Museum of Future Government",
    "URL": ""
  },
  {
    "2020": "Policies and norms around privacy in age of data breaches & IoT becomes a regulatory and ethical issue for government.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Digital privacy",
    "Category": "Governance",
    "buzz (google index)": "962,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Agile Services. Public services follow the path of startups like Uber - digital, user-friendly, agile - satisfies demand.",
    "2050": "Public Service EcoSystem. Police and other authorities treated \u0003like any other service providers - i.e. \u0003can be rejected and an alternative \u0003sought. Technology assists with this \u0003(e.g. police bodycams).",
    "Innovation / Development": "Consumerised public services",
    "Category": "Public Services",
    "buzz (google index)": 15,
    "type": "innovation",
    "now": "Citizens are more aware of their rights, have better access to info and higher expectations of services.",
    "line between 2020 & 2030": "Franchised Services. Business style models for public services \u0003- especially utilities, education, \u0003healthcare - become the \u0003international norm.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, McKinsey, PwC",
    "URL": ""
  },
  {
    "2020": "Technology-enabled self-service of government services (vehicle registration, income tax etc) expands.",
    "2030": "public sector organisations transform from big, all-in-one giants to small, flexible, purpose-driven entities.",
    "2050": "",
    "Innovation / Development": "Self service public services",
    "Category": "Public Services",
    "buzz (google index)": 4,
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Hyperlocal services. Neighbourhoods crowdfund their own needs. Services like higher education partially released from government.",
    "beyond": "Operational shortcomings addressed using tech and citizen input. One online space for all services, and one physical space in each locale streamlines govt.",
    "": "",
    "Source": "Deloitte, Museum of Future Government",
    "URL": ""
  },
  {
    "2020": "Medical tourism, outsourcing service delivery, best-in-class governments help other governments, etc.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Borderless public service markets",
    "Category": "Public Services",
    "buzz (google index)": "28,300",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte, KMPG",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Small direct payments using mobile payment apps, for use of public services, e.g. parks, hospitals.",
    "2050": "",
    "Innovation / Development": "Innovative Pricing Models",
    "Category": "Public Services",
    "buzz (google index)": "12,600",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Pay-as-you-go systems for public services, which helps to balance demand and provision. Fuel tax replaced with mileage fees.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "Immigration policies are relaxed as a result of globalisation, improved education and shortage of local talent. Refugees increase as resources grow scarce in parts of the world.",
    "2030": "",
    "2050": "Major cities will increase in population by 20.6% as urbanisation continues (by contrast, non-cities population will increase by 12.3% with general population growth).",
    "Innovation / Development": "Global migration",
    "Category": "Demographics",
    "buzz (google index)": "838,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Global citizens, using sharing economy, locate themselves anywhere in the world",
    "beyond": "",
    "": "",
    "Source": "Deloitte, UK Gov",
    "URL": ""
  },
  {
    "2020": "Policies have to take into account an increasingly large dependent segment. Pension reforms to reduce intergenerational inequality, e.g. raising the age of retirement, changing eligibility etc.",
    "2030": "Aging population. Longer lifespans, higher IQ, restoration of hearing and vision etc, all pose regulatory and ethical challenges. Older employed saturate the jobs market.",
    "2050": "Aged Population. Majority of the adult population now \u0003over 65 has substantial effect\non governmental & social policy and make-up.",
    "Innovation / Development": "Aging population",
    "Category": "Demographics",
    "buzz (google index)": "4,650,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Population aging pushes healthcare & pension spending up 4.4% of GDP by 2030. 13% of the world population is 65+ (versus 8% today)",
    "beyond": "Gerontocracy: The ageing population wields all the power, the young live as outsiders.",
    "": "",
    "Source": "Deloitte, KMPG",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Decline of the working age population impacts economic policy.",
    "2050": "",
    "Innovation / Development": "Population decline in west",
    "Category": "Demographics",
    "buzz (google index)": "1,400,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Nations with young populations, e.g. India, see economic growth stem from large working-age segment.",
    "2030": "By 2030 China and India will account for 35% of world population",
    "2050": "",
    "Innovation / Development": "Population growth in east",
    "Category": "Demographics",
    "buzz (google index)": "1,400,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte, KMPG",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Socio-economic status of women",
    "Category": "Demographics",
    "buzz (google index)": "7,340,000",
    "type": "development",
    "now": "Declining birthrates as perception of women as homemakers fades. Women expand the global workforce, influencing political and economic policy worldwide.",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Slums continue to grow - providing infrastructure and amenities to poverty-stricken urban areas become important policy points. Number of people living in city slums to double by 2030 (from 1bn to 2bn)",
    "2050": "",
    "Innovation / Development": "Megacities",
    "Category": "Transport & Cities",
    "buzz (google index)": "2,130,000",
    "type": "development",
    "now": "Around 7% of people live in cities with 8-figure populations.",
    "line between 2020 & 2030": "Urbanisation and city growth creates megacities - near-autonomous hubs where initatives can be tested. No. of megacities (pop 10m+) will increase from 20 today to 37 in 2025",
    "beyond": "Seasteading: autonomous modular city states floating on oceans.",
    "": "",
    "Source": "Deloitte, The Economist, KMPG, UN",
    "URL": ""
  },
  {
    "2020": "Major tech companies build experimental smart cities, which include things like heated roads, modular housing, clean energy, autonomous vehicles, high-speed networks etc.",
    "2030": "The streets will speak, literally. Offering information and services.",
    "2050": "Cost of living lowered, crime reduced 30-40%, first responders arrive 2-17mins faster, commute times cut 15-20%, impact of air pollution reduced 8-15%, emissions lowered 10-15%, solid waste & water use cut, public report problems & weigh in on planning, neighbours are linked, 1-3% boost in employment.",
    "Innovation / Development": "Smart Cities",
    "Category": "Transport & Cities",
    "buzz (google index)": "14,500,000",
    "type": "innovation",
    "now": "Smart city applications deployed in at least 50 cities globally. Key sectors: security, utilities, healthcare, & economic development, housing & community.",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Business Insider, Museum of Future Gov, McKinsey",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Architecture and ecology blend to bring eco-design principles to densely populated urban spaces, compact cities where roads & cars are eliminated, green climate tech installed & access to open spaces & nature calms inhabitants of such an intense space.",
    "2050": "",
    "Innovation / Development": "Arcology",
    "Category": "Transport & Cities, Climate",
    "buzz (google index)": "430,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "Green roofs, living walls, elevated walkways and cycleways, vertical gardening and aquaponics, semi-unclosed micro-climates in public spaces, bio-mimicry (emulating nature) on urban rivers and waterfronts.",
    "": "",
    "Source": "Arcosanti, UK Gov.",
    "URL": ""
  },
  {
    "2020": "Rideshares, food sharing, skills sharing etc., changes the way cities operate and reduces pressure on government services and infrastructure.",
    "2030": "",
    "2050": "Reputation Economy. Ebay style ratings of workers & employers \u0003creates a technology-mediated\nmarketplace where reputation is the singular currency.",
    "Innovation / Development": "Sharing economy",
    "Category": "Transport & Cities",
    "buzz (google index)": "5,530,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Driverless vehicles successfully emerge, using a combination of deep machine learning & computer vision for object recognition.",
    "2030": "",
    "2050": "Driverless vehicles unbiquitous. High-value real estate currently used for parking freed up for other uses.",
    "Innovation / Development": "Driverless vehicles",
    "Category": "Transport & Cities, Technology",
    "buzz (google index)": "510,000",
    "type": "innovation",
    "now": "Driverless cars tested on roads in the UK, the US, & China.",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "UK Gov, Financial Times",
    "URL": ""
  },
  {
    "2020": "Tech companies racing to develop functional flying vehicles.",
    "2030": "",
    "2050": "Hypersonic aircrafts commonplace, but for the super-wealthy only.",
    "Innovation / Development": "Flying Cars",
    "Category": "Transport & Cities",
    "buzz (google index)": "2,740,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "Increasing manned and unmanned aerial vehicle traffic creates difficult and expensive scenarios for city-planners and legislators",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "Packages might be delivered to your house by drones.",
    "2030": "UAVs used in search & rescue, to deliver medicines & provide internet access in remote locations, to guide blind runners & more.",
    "2050": "",
    "Innovation / Development": "Unmanned aerial vehicles",
    "Category": "Transport & Cities, Technology",
    "buzz (google index)": "4,040,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Drones routinely used for policing, geographical surveys, maritime patrol, etc",
    "beyond": "",
    "": "",
    "Source": "Deloitte, CB Insights",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Govt investment in connectivity tech to encourage flexible working arrangements, e.g. telecommuting, to reduce pressure on congested cities & overloaded transport systems.",
    "2050": "",
    "Innovation / Development": "Infrastructure bottlenecks",
    "Category": "Transport & Cities",
    "buzz (google index)": "112,000",
    "type": "development",
    "now": "Governments need to modernise existing infrastructure - but struggle with cost and vision.",
    "line between 2020 & 2030": "Political parties campaign on effectiveness. Tackling and reforming the bureacracy becomes a priority campaign issue.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Verve, McKinsey, KMPG",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "By 2050, Hyperloops - supersonic vehicles fired down enormous vaccum tubes - maybe a widespread form of public transport.",
    "Innovation / Development": "Hyperloop",
    "Category": "Transport & Cities, Technology",
    "buzz (google index)": "10,700,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Business Insider",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Global levels of public net debt are set to reach 98% of GDP by 2035. Reducing debt becomes a priority to protect the economy from future shocks.",
    "2050": "Futarchy: policies tied up with market speculation. When the market estimate of welfare is higher for adopting a policy than for not adopting a policy, that proposal becomes law.",
    "Innovation / Development": "Post-GDP",
    "Category": "Economics",
    "buzz (google index)": "11,300",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Globalisation of the economy = greater risk for international-scale financial catastrophes. National fiscal regulations need to line up with international regulations to prevent major problems.",
    "beyond": "Alternatives to GDP take hold. Holistic yardsticks for national progress, e.g. sustainability, health, inclusion, personal freedom... replace GDP as primary measure.",
    "": "",
    "Source": "Deloitte, Journal of Communication Inquiry, KMPG",
    "URL": ""
  },
  {
    "2020": "More micro-entrepreneurs (e.g. Etsy sellers, Uber drivers). Regulation & tax upheavals to support tech-informed class of individual workers.",
    "2030": "Re-learning Economy. National competitiveness relies on ability to continually retrain workers to keep up with changing environment & technologies.",
    "2050": "",
    "Innovation / Development": "Patchwork careers",
    "Category": "Economics",
    "buzz (google index)": 3730,
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Government workforce expanded to include partnership talent, borrowed talent, freelance talent, open-source talent, home-working talent, gig talent.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Aging workforces and lack of skilled technical talent drives freelance economy. Governments work with companies and organisations to address skills gap - a nation's talent levels drive their economy.",
    "2030": "Expanding middle class. 60% of the global population are middle class, up from 27% in 2009. Knowledge workers dominate the market. But who performs all the manual labour?",
    "2050": "Talent recognised as vital for national success. International borders lowered and remodelled to encourage talent migration.",
    "Innovation / Development": "The talent gap",
    "Category": "Economics",
    "buzz (google index)": "107,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Performance-related salaries. Payment-for-results models become mainstream, shifts financial risk from government to investors.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Income inequalisation",
    "Category": "economics",
    "buzz (google index)": "799,000",
    "type": "development",
    "now": "Global income inequality rising. Governments prioritise access to healthcare, education, etc., for the poorest segments.",
    "line between 2020 & 2030": "Universal Basic Income. As robotics and automation replace jobs, nations experiment with giving their citizens flat-rate salaries, instead of benefits.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Open Banking",
    "Category": "Economics",
    "buzz (google index)": "1,220,000",
    "type": "innovation",
    "now": "Lightweight banking services on offer, without the need to maintain heavy banking infrastructure nor comply with complex regulations. Traditional banking under threat.",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Business Insider",
    "URL": ""
  },
  {
    "2020": "Mobile payments, digital currencies are fully mainstream. Digital theft protection is a primary concern for governments.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Digital currencies",
    "Category": "Economics, Technology",
    "buzz (google index)": "2,110,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Bitcoin-based charities creating trust through smart contracts and online reputation systems and allowing donors to see where their donations go through a secure and transparent ledger.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Economic power and wealth moves from west to east, shifting global politics.",
    "2050": "China and India account for 25% of global GDP",
    "Innovation / Development": "Wealth movement west to east",
    "Category": "Economics",
    "buzz (google index)": "18,100",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Tipping Point. Developing countries account for 57% of global GDP.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, KMPG",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "Shift from industry-based sectors to issue-based sectors, e.g. creative industries, agri-food and water, wellbeing and welfare.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Industrial Sector changes",
    "Category": "Industry",
    "buzz (google index)": 6430,
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "PwC",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Innovating to zero",
    "Category": "Industry",
    "buzz (google index)": "46,500",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Innovating to zero, e.g. 'zero defects', becomes common goal.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "Long-term investment in major infrastructure projects bring government and businesses together.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Patient Capitalism",
    "Category": "Industry",
    "buzz (google index)": "80,600",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Second industrial revolution - mass customization, reduced cost of labour, increasing intellectual property theft.",
    "2050": "",
    "Innovation / Development": "3D printing",
    "Category": "Industry, Technology",
    "buzz (google index)": "46,100,000",
    "type": "innovation",
    "now": "Extensively used in industry for prototyping & proof-of-concept models. Use in art & marketing also on the rise.",
    "line between 2020 & 2030": "Anybody can invent new products & have them made to order at their local 3D printing hub.",
    "beyond": "additive manufacturing, 3D printing of low-cost housing and artifical limbs",
    "": "",
    "Source": "Deloitte, Forbes",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "International cybersecurity in era of open government, open data, and govt. social media is a leading social issue.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Digital security",
    "Category": "Crime & Security",
    "buzz (google index)": "2,650,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "New data-breach prevention laws mandate tighter and more expensive stewardship of citizen and government data.",
    "beyond": "",
    "": "",
    "Source": "Word Economic Forum, KMPG",
    "URL": ""
  },
  {
    "2020": "Open government and digital services lower corruption rates in developed economies. Using tech and citizen-consumer action to tackle corruption elsewhere becomes a priority.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Corruption reduction",
    "Category": "Crime & Security",
    "buzz (google index)": 11500,
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Formal global communication channels established to address emerging cyber threats.",
    "2050": "",
    "Innovation / Development": "Cyber-warfare",
    "Category": "Crime & Security",
    "buzz (google index)": "1,300,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "As threats easily transcend national borders, emerging cyber security threats call for international cooperation and information sharing, especially during a crisis",
    "beyond": "",
    "": "",
    "Source": "KMPG",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "Social media used increasingly to organize protests, shape social narrative, and pressurise governments and policy.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Social Media",
    "Category": "Technology",
    "buzz (google index)": "1,130,000,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "50% of global population have internet by 2030, up from 34% in 2012.",
    "2050": "",
    "Innovation / Development": "5G Cellular networks",
    "Category": "Technology",
    "buzz (google index)": "289,000,000",
    "type": "innovation",
    "now": "From 2019 phones will start to utilise the faster and more efficent next-generation mobile internet.",
    "line between 2020 & 2030": "Next generation, ultra fast wireless mobile connections make communication radically more detailed, faster etc",
    "beyond": "",
    "": "",
    "Source": "KMPG, Qualcomm",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Hospitals and other healthcare organizations create centralized and secure blockchain databases, storing medical records and share only with patients and authorized custodians.",
    "2050": "Blockchain reduced bureaucracy increases security, efficiency and transparency in government. Welfare and unemployment benefits more easily verified and distributed. Electoral votes could be counted and verified for legitimacy.",
    "Innovation / Development": "Blockchain",
    "Category": "Technology",
    "buzz (google index)": "188,000,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Blockchain acts a bulkwalk against cybercrime. Decentralized, distributed systems creates more robust defenses against data breaches.",
    "beyond": "",
    "": "",
    "Source": "Forbes",
    "URL": ""
  },
  {
    "2020": "Governments attempt to integrate IoT tech, using data to improve healthcare, transport, security, defence, infrastructure etc.",
    "2030": "Connecting objects with infrastructure (e.g. cars and roads) drastically reduce traffic accidents and deaths. And empower rapid disaster response for natural disasters.",
    "2050": "",
    "Innovation / Development": "Internet of Things",
    "Category": "Technology",
    "buzz (google index)": "309,000,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Microsoft, Business Insider",
    "URL": ""
  },
  {
    "2020": "Governments open up their geospatial tech databases, impacting traffic management, healthcare, infrastructure planning, etc.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Geographic Information Systems (GIS)",
    "Category": "Technology",
    "buzz (google index)": "161,000,000",
    "type": "innovation",
    "now": "Organizations in virtually every field are using GIS to identify problems & understand trends.",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte, ESRI",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Open Data Platforms",
    "Category": "Technology",
    "buzz (google index)": "74,900",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "The release and sharing of data across all governments and industries becomes\na societal norm.",
    "beyond": "",
    "": "",
    "Source": "Deloitte",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Regulated Technologies",
    "Category": "Technology",
    "buzz (google index)": "5,650",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "The capacity of all emergent, next generation tech is carefully and quickly assessed as a priority by governments.",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "AI Hiring. Increasingly used in HR. Analytics tools are intelligently selecting candidates, identifying employees’ career options, and coaching managers on improving their leadership skills.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Commercial AI",
    "Category": "Artificial intelligence",
    "buzz (google index)": "28,900",
    "type": "innovation",
    "now": "Passive AI. Used for product development, automating rote tasks, improving services, & monitoring employees.",
    "line between 2020 & 2030": "AI Assistants. Chatbots & digital assistants interact with job candidates, identify and score video interviews, and understand the sentiment of engagement surveys.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Kellogg, FHI, Business Insider",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "Machine learning + geonomics results in highly individualized medical treatments.",
    "Innovation / Development": "Machine Learning",
    "Category": "Artificial intelligence",
    "buzz (google index)": "67,000,000",
    "type": "innovation",
    "now": "Machine learning is being used gain competitive insights in financial services, healthcare, oil & gas, marketing & sales, & transport.",
    "line between 2020 & 2030": "Intelligent, learning machines mimick human thought process. Used to automate administrative tasks, assist in problem solving etc.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Kellogg, FHI, Business Insider, SAS",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "Security cameras conduct marketing research on passing consumers. Healthcare scanners help technicians. Guided surgeries are are the norm. Farm equipment increasingly autonomous.",
    "2050": "",
    "Innovation / Development": "Computer / machine vision",
    "Category": "Artificial intelligence",
    "buzz (google index)": "22,500,000",
    "type": "innovation",
    "now": "Major user-generated content platforms use computer vision to categorise posts & provide advanced editing options to end-users.",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Forbes, VisionOnline",
    "URL": ""
  },
  {
    "2020": "Computers can read documents & answer questions about the content.",
    "2030": "AI will be used for answering complex questions: AI systems will read millions of pages, and understand the context.",
    "2050": "",
    "Innovation / Development": "Machine Reading & comprehension",
    "Category": "Artificial intelligence",
    "buzz (google index)": "175,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Microsoft",
    "URL": ""
  },
  {
    "2020": "Machines that can read and translate any written or spoken language further dissolve cultural and even state boundaries.",
    "2030": "Computers converse fluently in natural language.  Assist citizens to do the same via their mobile devices.",
    "2050": "",
    "Innovation / Development": "Natural Language processing",
    "Category": "Artificial intelligence",
    "buzz (google index)": "9,340,000",
    "type": "innovation",
    "now": "Smartphones suggest words based on context as we type. Businesses use NLP to explore search terms consumers use & target their advertising.",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "Deloitte, Kellogg, FHI, Business Insider, Forbes",
    "URL": ""
  },
  {
    "2020": "Robots which can read emotions and converse will become our friends.",
    "2030": "800 million global workers are replaced by robots by 2030.",
    "2050": "",
    "Innovation / Development": "Advanced Robotics",
    "Category": "Artificial intelligence",
    "buzz (google index)": "953,000",
    "type": "innovation",
    "now": "Hundreds of thousands of robots are already in operation in retail and manufacturing.  Next generation collaborative robots, or “co-bots,” that work side by side with workers in factories. Some dangerous jobs are outsourced to robots, e.g. welding, bomb-disposal.",
    "line between 2020 & 2030": "Home robots help elders with everyday tasks, predict when they need to use the toilet, detect falls & more.",
    "beyond": "",
    "": "",
    "Source": "Deloitte, CNN, Kellogg, FHI, Business Insider, Guardian",
    "URL": "https://www.theguardian.com/world/2018/feb/06/japan-robots-will-care-for-80-of-elderly-by-2020"
  },
  {
    "2020": "",
    "2030": "",
    "2050": "",
    "Innovation / Development": "",
    "Category": "",
    "buzz (google index)": "",
    "type": "",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "",
    "URL": ""
  },
  {
    "2020": "The drive to pioneer efficient and \u0003affordable energy solutions drives \u0003innovation in the energy, technology \u0003and industry sectors.",
    "2030": "The sharing economy meets renewables, propelling the growth of community solar, crowd-funding, and other forms of shared participation in renewable energy deployment.",
    "2050": "A full-scale “grid independence” could be underway with smart- and micro-grids able to store and modulate the viable energy output from renewables.",
    "Innovation / Development": "Smart Sustainable Energy",
    "Category": "Climate",
    "buzz (google index)": "5,460,000",
    "type": "innovation",
    "now": "",
    "line between 2020 & 2030": "Passive climate control systems, innovative water/sewage treatment flows, green building materials and high-performance recycling technology",
    "beyond": "Renewables as competitive as fossil fuels.",
    "": "",
    "Source": "Arcosanti, Deloitte",
    "URL": ""
  },
  {
    "2020": "Supranational and national bodies further legislate on emissions. Single use plastic bans, new ecological building standards, arcology becomes the legislative norm.",
    "2030": "Government regulations shift from 'informing & advising' to 'banning & penalizing'. Regulations to include, for example, restricting water, food, energy during stress events, phasing out high energy consuming tech, banning older cars, banning plastic bags, requiring construction to meet energy efficiency standards etc.",
    "2050": "Growth within limits\" is the inward developmental mindset necessary to reduce our ecological footprint.",
    "Innovation / Development": "Climate Legislation",
    "Category": "Climate",
    "buzz (google index)": "143,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Adaptive GAction. Policy on climate change switches from ineffective top-down system of IPCC initiatives to a bottom-up approach, engaging all levels of power and acting locally.",
    "beyond": "Businesses cannot operate unless they are sustainable at their core.",
    "": "",
    "Source": "St. Anthony's International Review, KMPG, Deloitte",
    "URL": ""
  },
  {
    "2020": "Top priority area for WEF, UN etc.",
    "2030": "40% global gap between water supply and demand by 2030",
    "2050": "Military-led responses to natural disasters become the norm.",
    "Innovation / Development": "Declining natural resources",
    "Category": "Climate",
    "buzz (google index)": "17,500",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "Food prices predicted to double between 2010 and 2030",
    "beyond": "",
    "": "",
    "Source": "Deloitte, PWC, Humanitarian Practice Network, KMPG",
    "URL": ""
  },
  {
    "2020": "Lab-grown meat becomes affordable.",
    "2030": "",
    "2050": "",
    "Innovation / Development": "Molecular Agriculture",
    "Category": "Climate",
    "buzz (google index)": "12,200",
    "type": "innovation",
    "now": "Veganism increasing in global population as ecological costs of meat industry become more apparent.",
    "line between 2020 & 2030": "Almost all meat-based foods replaced by high tech plant formulations, mimicking the taste, smell, and texture.",
    "beyond": "",
    "": "",
    "Source": "BBC",
    "URL": ""
  },
  {
    "2020": "",
    "2030": "",
    "2050": "Carbon capture, land weathering, ocean fertisilation - massive, costly bio-engineering projects implemented on a global scale - costing trillions of dollars, required to drawdown gigatons of surplus carbon dioxide from the atmosphere.",
    "Innovation / Development": "Climate engineering",
    "Category": "Cimate",
    "buzz (google index)": "459,000",
    "type": "development",
    "now": "",
    "line between 2020 & 2030": "",
    "beyond": "",
    "": "",
    "Source": "KMPG",
    "URL": ""
  }
]